export const SUCCESS_MSG = {
    200: "Request successful",
    201: "Resource created successfully",
    202: "Request accepted",
    203: "Non-authoritative information",
    204: "No content",
    205: "Reset content",
    206: "Partial content",
    207: "Multi-status",
    208: "Already reported",
    226: "IM used",
    300: "Multiple choices",
    301: "Moved permanently",
    302: "Found (Moved temporarily)",
    303: "See other",
    304: "Not modified",
    305: "Use proxy",
    307: "Temporary redirect",
    308: "Permanent redirect"
};

export const ERROR_MSG = {
    400: "Bad request - Invalid data provided",
    401: "Unauthorized - Please login first",
    402: "Payment required",
    403: "Forbidden - You don't have permission",
    404: "Resource not found",
    405: "Method not allowed",
    406: "Not acceptable",
    407: "Proxy authentication required",
    408: "Request timeout",
    409: "Conflict - Resource already exists",
    410: "Gone - Resource no longer available",
    411: "Length required",
    412: "Precondition failed",
    413: "Payload too large",
    414: "URI too long",
    415: "Unsupported media type",
    416: "Range not satisfiable",
    417: "Expectation failed",
    418: "I'm a teapot",
    421: "Misdirected request",
    422: "Validation failed",
    423: "Locked",
    424: "Failed dependency",
    425: "Too early",
    426: "Upgrade required",
    428: "Precondition required",
    429: "Too many requests - Try again later",
    431: "Request header fields too large",
    451: "Unavailable for legal reasons",
    500: "Internal server error",
    501: "Not implemented",
    502: "Bad gateway",
    503: "Service unavailable",
    504: "Gateway timeout",
    505: "HTTP version not supported",
    506: "Variant also negotiates",
    507: "Insufficient storage",
    508: "Loop detected",
    510: "Not extended",
    511: "Network authentication required"
};
